apiVersion: kubeflow.tkestack.io/v1alpha1
kind: JupyterNotebook
metadata:
  name: jupyternotebook-simple
spec:
  # Disable the password and token based auth in this example,
  # please do not do it in PROD.
  auth:
    mode: disable
  template:
    metadata:
      labels:
        notebook: simple
    spec:
      containers:
        - name: notebook
          image: jupyter/base-notebook:python-3.9.7
          command: ["tini", "-g", "--", "start-notebook.sh"]
