# permissions for end users to view jupyterkernels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jupyterkernel-viewer-role
rules:
- apiGroups:
  - kubeflow.tkestack.io
  resources:
  - jupyterkernels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubeflow.tkestack.io
  resources:
  - jupyterkernels/status
  verbs:
  - get
