# permissions for end users to edit jupyterkernelspecs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jupyterkernelspec-editor-role
rules:
- apiGroups:
  - kubeflow.tkestack.io
  resources:
  - jupyterkernelspecs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeflow.tkestack.io
  resources:
  - jupyterkernelspecs/status
  verbs:
  - get
