apiVersion: kubeflow.tkestack.io/v1alpha1
kind: JupyterKernel
metadata:
  name: jupyterkernel-sample
spec:
  template:
    metadata: 
      app: enterprise-gateway
      component: kernel
    spec:
      restartPolicy: Never
      containers:
        - name: kernel
          image: ghcr.io/skai-x/jupyter-kernel-py:2.6.0
